apiVersion: 1

contactPoints:
  - orgId: 1
    name: Slack Police112
    receivers:
      - uid: slack-police112
        type: slack
        settings:
          url: SLACK_WEBHOOK_URL_REDACTED
          recipient: "#112-alerts"
          mentionChannel: ""
          token: ""
          username: "Grafana Police112"
          icon_emoji: ":rotating_light:"
          title: '{{ template "slack.default.title" . }}'
          text: >-
            {{ range .Alerts }}
            *{{ .Labels.alertname }}* | Severity: {{ .Labels.severity }}
            {{ .Annotations.summary }}
            {{ .Annotations.description }}
            {{ end }}
        disableResolveMessage: false
