spring:
  config:
    activate:
      on-profile: prod
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    root: WARN
    com.police.iot: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" # In real prod, use JSON formatter

app:
  security:
    jwt:
      dev:
        enabled: false
