spring:
  application:
    name: command-service
  profiles:
    default: dev
  main:
    log-startup-info: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: 8082
  shutdown: graceful
  tomcat:
    threads:
      max: ${SERVER_TOMCAT_MAX_THREADS:200}
      min-spare: ${SERVER_TOMCAT_MIN_SPARE_THREADS:20}
    max-connections: ${SERVER_TOMCAT_MAX_CONNECTIONS:8192}
    accept-count: ${SERVER_TOMCAT_ACCEPT_COUNT:100}

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/traces}
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,metrics"
  endpoint:
    health:
      probes:
        enabled: true
        add-additional-paths: true
      show-details: always
      group:
        liveness:
          include: livenessState,ping
        readiness:
          include: readinessState,db
        startup:
          include: readinessState
    prometheus:
      enabled: true

app:
  security:
    jwt:
      dev:
        enabled: false
