CREATE TABLE T_OFFICER (
    ID UUID PRIMARY KEY,
    TENANT_ID VARCHAR(255) NOT NULL,
    USER_ID VARCHAR(255) NOT NULL,
    OFFICER_NAME VARCHAR(255),
    BADGE_NUMBER VARCHAR(255) UNIQUE,
    STATUS VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE T_PATROL_VEHICLE (
    ID UUID PRIMARY KEY,
    TENANT_ID VARCHAR(255) NOT NULL,
    PLATE_NUMBER VARCHAR(255) NOT NULL UNIQUE,
    VEHICLE_TYPE VARCHAR(100),
    EDGE_NODE_ID VARCHAR(255),
    STATUS VARCHAR(50),
    LOCATION TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE T_INCIDENT (
    ID UUID PRIMARY KEY,
    TENANT_ID VARCHAR(255) NOT NULL,
    TYPE VARCHAR(100),
    DESCRIPTION TEXT,
    LOCATION TEXT,
    SEVERITY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    OFFICER_ID UUID REFERENCES T_OFFICER(ID),
    VEHICLE_ID UUID REFERENCES T_PATROL_VEHICLE(ID)
);

CREATE INDEX IDX_OFFICER_TENANT ON T_OFFICER(TENANT_ID);
CREATE INDEX IDX_VEHICLE_TENANT ON T_PATROL_VEHICLE(TENANT_ID);
CREATE INDEX IDX_INCIDENT_TENANT ON T_INCIDENT(TENANT_ID);
