CREATE TABLE T_IDEMPOTENCY_RECORD (
    ID BIGSERIAL PRIMARY KEY,
    TENANT_ID VARCHAR(255) NOT NULL,
    ROUTE VARCHAR(255) NOT NULL,
    HTTP_METHOD VARCHAR(10) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(255) NOT NULL,
    REQUEST_HASH VARCHAR(64) NOT NULL,
    RESPONSE_STATUS INT,
    RESPONSE_BODY TEXT,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX UK_IDEMPOTENCY_SCOPE
    ON T_IDEMPOTENCY_RECORD(TENANT_ID, ROUTE, HTTP_METHOD, IDEMPOTENCY_KEY);

CREATE INDEX IDX_IDEMPOTENCY_CREATED_AT ON T_IDEMPOTENCY_RECORD(CREATED_AT);
