spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:29092

logging:
  level:
    root: INFO
    com.police.iot: DEBUG
