spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD} # Required in prod
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    properties:
      security.protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
      # sasl.mechanism: PLAIN
      # sasl.jaas.config: ...

logging:
  level:
    root: WARN
    com.police.iot: INFO
