server {
    listen 8090;
    server_name _;

    root /usr/share/nginx/html;
    index dashboard.html;

    location / {
        try_files $uri /dashboard.html;
    }

    # Reverse proxy: /device/* → device-service:8081/*
    location /device/ {
        proxy_pass         http://device-service:8081/;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_read_timeout 30s;
    }

    # Reverse proxy: /event/* → event-service:8083/*
    location /event/ {
        proxy_pass         http://event-service:8083/;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_read_timeout 30s;
    }
}
